/**
 * Build script to inject environment variables into the app
 * Run this before deploying:  node build-env.js
 * 
 * For Render static site deployment: 
 * 1. Set API_KEY in Render's environment variables
 * 2. Set build command to: node build-env.js
 * 3. Set publish directory to: ./
 */

const fs = require('fs');
const path = require('path');

// Get API key from environment variable
const API_KEY = process. env.API_KEY || '';

if (!API_KEY) {
    console. warn('⚠️  Warning: API_KEY environment variable is not set! ');
    console.warn('   The app will require users to enter their own API key.');
} else {
    console.log('✅ API_KEY found, injecting into application...');
}

// Create the env-config.js file that will be loaded by the app
const envConfig = `// Auto-generated by build-env.js - DO NOT EDIT MANUALLY
// This file is generated during the build process
window.ENV = {
    API_KEY: "${API_KEY}",
    BUILD_TIME: "${new Date().toISOString()}"
};
`;

// Write the config file
fs.writeFileSync(path. join(__dirname, 'env-config. js'), envConfig);

console.log('✅ env-config.js generated successfully! ');
console.log(`   Build time: ${new Date().toISOString()}`);
